/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.HulkController;
import Controller.HulkControllerNewMainChat;
import Controller.PostOfficeCenter;
import Controller.SendMessageController;
import Controller.SettingsSmasher;
import Model.GammaCellRenderer;
import Model.GammaMachine;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.NoSuchPaddingException;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ATX
 */
public class NewChatView extends javax.swing.JPanel {

    /**
     * Creates new form NewChatView
     */
    DefaultListModel<String> MainChat = new DefaultListModel<>();
    public Mainwindow mainwindow;
    private PostOfficeCenter pobox;
    public NewChatView() {
        initComponents();
        plainTextArea.setLineWrap(true);
        plainTextArea.setWrapStyleWord(true);
        Cipherarea.setLineWrap(true);
        pobox = new PostOfficeCenter();
        try {
            gammaLabel.addMouseListener(new HulkControllerNewMainChat(this, (new GammaMachine())));
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(NewChatView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(NewChatView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            SettingsButton.addMouseListener(new HulkControllerNewMainChat(this, (new GammaMachine())));
            //MessageArea.setModel(MainChat);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(NewChatView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(NewChatView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public NewChatView(Mainwindow MainView) {
        mainwindow = MainView;
        initComponents();
        plainTextArea.setLineWrap(true);
        plainTextArea.setWrapStyleWord(true);
        Cipherarea.setLineWrap(true);
        pobox = new PostOfficeCenter();
        try {
            gammaLabel.addMouseListener(new HulkControllerNewMainChat(this, (new GammaMachine())));
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(NewChatView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(NewChatView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            SettingsButton.addMouseListener(new HulkControllerNewMainChat(this, (new GammaMachine())));
            //MessageArea.setModel(MainChat);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(NewChatView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(NewChatView.class.getName()).log(Level.SEVERE, null, ex);
        }
        Thread x = new Thread(pobox);
        x.start();
        
        SendButton.addMouseListener( new SendMessageController(this, pobox.getOutputQueue(), pobox.getUserMessageQueue()));
        
    }
    
    public  JTextArea getCipherarea(){
        return Cipherarea;
    }
    
    public JTextArea getPlaintextarea(){
        return plainTextArea;
    }
    
    public JList getMainMessage(){
        return MessageArea;
    }
    
    public DefaultListModel getMainChat(){
        return MainChat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageArea = new javax.swing.JList<>();
        jToolBar1 = new javax.swing.JToolBar();
        SettingsButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        plainTextArea = new javax.swing.JTextArea();
        gammaLabel = new javax.swing.JButton();
        SendButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Cipherarea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(69, 93, 43));
        setMaximumSize(new java.awt.Dimension(400, 647));
        setMinimumSize(new java.awt.Dimension(400, 647));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 87, 113), 5));

        MessageArea.setModel(MainChat);
        MessageArea.setCellRenderer(new GammaCellRenderer());
        jScrollPane1.setViewportView(MessageArea);

        jTabbedPane1.addTab("AvengerChatName", jScrollPane1);

        jToolBar1.setRollover(true);

        SettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SettingsSmall.png"))); // NOI18N
        SettingsButton.setFocusable(false);
        SettingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SettingsButton.setName("SettingsButton"); // NOI18N
        SettingsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(SettingsButton);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FriendsSmall.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Transfer File");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hulkmonstersmall.png"))); // NOI18N
        jButton5.setToolTipText("Logout");

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));

        plainTextArea.setBackground(new java.awt.Color(0, 0, 0));
        plainTextArea.setColumns(20);
        plainTextArea.setForeground(new java.awt.Color(51, 204, 0));
        plainTextArea.setLineWrap(true);
        plainTextArea.setRows(5);
        plainTextArea.setToolTipText("Message Area");
        jScrollPane2.setViewportView(plainTextArea);

        jTabbedPane2.addTab("tab1", jScrollPane2);

        gammaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GammaSignSmall.png"))); // NOI18N
        gammaLabel.setName("GammaRaySign"); // NOI18N

        SendButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/send_icon_small.png"))); // NOI18N

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Cipherarea.setBackground(new java.awt.Color(0, 0, 0));
        Cipherarea.setColumns(20);
        Cipherarea.setForeground(new java.awt.Color(255, 255, 51));
        Cipherarea.setRows(5);
        jScrollPane3.setViewportView(Cipherarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gammaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SendButton)
                                        .addGap(8, 8, 8))
                                    .addComponent(jTabbedPane2))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gammaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Cipherarea;
    private javax.swing.JList<String> MessageArea;
    private javax.swing.JButton SendButton;
    private javax.swing.JButton SettingsButton;
    public javax.swing.JButton gammaLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea plainTextArea;
    // End of variables declaration//GEN-END:variables
}
